/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    scala
    `java-library`
    id("org.mbari.commons.java-conventions")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    api(project(":jcommons"))
    implementation("org.scala-lang:scala3-library_3:3.3.4")
    implementation("com.github.wendykierp:JTransforms:3.2")
    implementation("org.typelevel:spire_3:0.18.0")
    implementation("org.apache.commons:commons-math3:3.6.1")
    implementation("org.apache.commons:commons-email:1.6.0")
    testImplementation("org.scalameta:munit_3:1.3.0")
    testImplementation("junit:junit:4.13.2")
}

// Override the default artifactId for Maven to adhere to Scala conventions
extra["artifactIdForMaven"] = "scommons_3"

description = "scommons"

